### ISSUE TITLE
Allow custom uTest frameworks

### ISSUE THREAD

**Issue by frgomes** [tkawachi/sbt-doctest#105]
## Background

``uTest`` can be configured via extension.
For example:

 1. create a class inside your ``src/test/scala`` like the example below:
```scala
package test.utest

class CustomFramework extends utest.runner.Framework {
  override def formatColor: Boolean =
    java.net.InetAddress.getLocalHost.getHostName != "jenkins.example.com"
}
```
 2. put this below into your ``build.sbt``:
```scala
testFrameworks += new TestFramework("test.utest.CustomFramework")
```
In the specific example above, you will disable colored output when running in Jenkins.

## About this issue

Remove line 76 from ``DoctestPlugin.scala``:
```scala
 testFrameworks += new TestFramework("utest.runner.Framework"),
```
The end user should be responsible for choosing whatever implementation of ``uTest`` is required.

*NOTE:* In this case, ``sbt-doctest`` is oblivious to ``utest.runner.Framework``, meaning that the end user is responsible for wiring ``uTest`` in his/her ``build.sbt``.

**Comment by frgomes** [comment]
@tkawachi :: In the description I suggest removing one line. However, this would break backwards compatibility. We would be jeopardizing the vast majority of common cases just because there are a few exceptions to the rule. It does not seem to be the right thing to be done.

Another possibility would be introducing another ``Setting``, say ``utestCustomFramework`` and doing something more or less like this:
```scala
testFrameworks += utestCustomFramework.value.getOrElse("utest.runner.Framework")
```
Thoughts?

**Comment by frgomes** [comment]
@tkawachi :: I've tried to lift my changes on ``sbt-doctest`` from another project by directly trying to download/compile ``sbt-doctest`` from GitHub, like this:

```scala
//file: project/sbt-doctest.sbt
lazy val root =
  (project in file("."))
    .dependsOn(doctest_frgomes)

lazy val doctest_frgomes = RootProject(uri("git://github.com/frgomes/sbt-doctest.git#0105-allow_custom_utest_frameworks"))
```

When I try to load my end-user project, if complain that it cannot find several dependencies:
```bash
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#scripted-plugin;1.1.0: not found
[warn]  :: com.typesafe.sbt#sbt-scalariform;1.3.0: not found
[warn]  :: com.timushev.sbt#sbt-updates;0.1.9: not found
[warn]  :: org.xerial.sbt#sbt-sonatype;1.0: not found
[warn]  :: com.jsuereth#sbt-pgp;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```
I suppose that ``sbt-doctest`` should provider a resolver for such dependencies, correct?
Any idea what the issue could be? By the way, I'm using SBT 1.1.0.
Thanks a lot.

**Comment by tkawachi** [comment]
I honestly don't know how often utest users use a custom framework. It will be enough to replace test frameworks like following if it isn't a typical case.

```scala
testFrameworks ~= (_.map { framework =>
    if (framework.implClassNames.toList == List("utest.runner.Framework")) { 
      new TestFramework("test.utest.CustomFramework")
    } else { 
      framework
    } 
  })
```

**Comment by tkawachi** [comment]
Or using `-=` and `+=` is more concise.

```scala
testFrameworks -= new TestFramework("utest.runner.Framework")
testFrameworks += new TestFramework("test.utest.CustomFramework")
```
