### ISSUE TITLE
Add support for MUnit

### ISSUE THREAD

**Issue by alexandru** [tkawachi/sbt-doctest#134]
Supporting [MUnit](https://scalameta.org/munit/blog/2020/02/01/hello-world.html) would be cool.

**Comment by arashi01** [comment]
Fixed by #175

@tkawachi, @xuwei-k Any chance of cutting a 0.9.9 release?

**Comment by tkawachi** [comment]
@arashi01  Thanks for reminding me. I've released it so you can try it out.

@xuwei-k  Also, thanks for always updating the library.
