### ISSUE TITLE
Error when using top-level functions or enum

### ISSUE THREAD

**Issue by i10416** [tkawachi/sbt-doctest#254]
I tried to use sbt-doctest in Scala 3 project but it failed to generate tests when I run test.   

```
error: expected class or object definition identifier
enum Foo {
^
error: expected start of definition
@main def bar: Unit =  ...
```

Does sbt-doctest support Scala 3 syntax?

**Comment by xuwei-k** [comment]
- https://github.com/tkawachi/sbt-doctest/pull/302
