### ISSUE TITLE
support other test libraries

### ISSUE THREAD

**Issue by xuwei-k** [tkawachi/sbt-doctest#51]

**Comment by frgomes** [comment]
For your information, I'm working on support for OTest, which is a small test library aiming ScalaJS.
https://github.com/frgomes/sbt-doctest

**Comment by joprice** [comment]
[utest](https://github.com/lihaoyi/utest) would be nice as well

**Comment by frgomes** [comment]
@joprice : Indeed. utest is small, simple and, most important of all, non intrusive.
Also, it's well supported by IntelliJ and can be employed with ScalaJS.

This is not the first time I add ScalaTest to a project and IntelliJ gets mad after that.
And when IntelliJ gets mad... I got mad! :-(

**Comment by frgomes** [comment]
This issue is generic and I suggest that it should be closed in favor of https://github.com/tkawachi/sbt-doctest/issues/78

**Comment by frgomes** [comment]
@joprice :: Support for uTest available from #78

**Comment by frgomes** [comment]
@tkawachi :: I suggest closing this issue.
If specific support for some specific test framework is needed... a specific issue should be opened.

**Comment by tkawachi** [comment]
Please feel free to open an issue for each test framework.
