### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by ceedubs** [tkawachi/sbt-doctest#56]
Firstly: thanks for the great plugin!

Scala 2.11 provides the `-Ywarn-unused-import` flag, which warns you about unused imports. It's handy for keeping your imports clean.

When using sbt-doctest without using property-based checks, one gets warnings for unused imports on:
```scala
import org.scalacheck.Arbitrary._
import org.scalacheck.Prop._
```

Would there be a fairly simple solution to avoiding this problem without completely disabling the flag in tests? Ideally they would only be included if there were actually property-based tests in the file.

**Comment by fthomas** [comment]
Thanks for the report, @ceedubs! I don't know an easy way to workaround this problem other than adding a property-based test, but it is fairly easy for the plugin to exclude the imports if they are not necessary, see #57.
