### ISSUE TITLE
should not depends on Scala2.10 compiler

### ISSUE THREAD

**Issue by xuwei-k** [tkawachi/sbt-doctest#6]
it should be configurable

**Comment by fthomas** [comment]
Maybe [scalaparse](https://github.com/lihaoyi/fastparse) is also an option.

**Comment by tkawachi** [comment]
https://github.com/lihaoyi/fastparse/tree/master/scalaparse/shared/src/main/scala/scalaparse This one?

**Comment by fthomas** [comment]
Yes. I don't know if it is suitable for sbt-doctest, but I thought I should mention it anyway.

**Comment by frgomes** [comment]
Imho the plugin should employ the Scala compiler which matches the Scala version used in the user project. If employing Scalariform implies on changing the source code and/or reformatting it even in memory or somewhere else ... it's not an option.

**Comment by jozic** [comment]
i have working code with getting comments with scalameta, but scalameta is only available for 2.11+, which means 2.10 won't be supported
@tkawachi let me know if you want to sacrifice 2.10 support for closing this issue

**Comment by tkawachi** [comment]
Moving from 2.10 means dropping support of sbt 0.13. sbt 1.0 was released almost one year ago. I feel it's Okay to go.

**Comment by jozic** [comment]
cool, I will send a PR a bit later
