### ISSUE TITLE
Support for scala fragments in markdown

### ISSUE THREAD

**Issue by rgladwell** [tkawachi/sbt-doctest#62]
Thinking of putting a PR together to optionally (you have to manually enable in your sbt) compile Scala fragments in Markdown, so for example if you had the following `README.md` file:

```
# Markdown Doctest Test

```scala
scala> import sbt_doctest.Main.abc
import sbt_doctest.Main.abc

scala> abc
res0: String = Hello, world!
```

It would compile this into a `READMEDoctest.scala` file.

Does this sound like something you guys would merge?

**Comment by fthomas** [comment]
So you are proposing to read test fragments not only from Scaladoc comments but also from Markdown files. That sounds great to me and I would use it in my projects right away. I guess that could be even extended to arbitrary files and not only Markdown.

**Comment by wookietreiber** [comment]
:+1:

**Comment by rgladwell** [comment]
@fthomas wouldn't other file types have to be judged on a case-by-case basis? For example, in the case of Markdown we have to look for ````scala` blocls

**Comment by tkawachi** [comment]
:+1: for markdown

**Comment by tkawachi** [comment]
Pull requests are always welcome :smile:

**Comment by fthomas** [comment]
@rgladwell I thought that the REPL prompt `scala>` could be enough to recognize test fragments. But this was just a half-baked idea.

BTW: A similar feature for tut was requested in https://github.com/tpolecat/tut/issues/59. The difference to the proposed format here is that there are no REPL prompts and the result is in comments
