### ISSUE TITLE
Add markdown files to watchSources

### ISSUE THREAD

**Issue by Jentsch** [tkawachi/sbt-doctest#67]
Hi,
it would be nice if a cycle in ```~test``` would also triggered by changes in a markdown file.

To do this I think something like
```scala
watchSources ++= (baseDirectory.value \ "README.md").get
```
 around [DoctestPluging Line 123](https://github.com/tkawachi/sbt-doctest/blob/master/src/main/scala/com/github/tkawachi/doctest/DoctestPlugin.scala#L123) would be helpful. But I'm not sure how to write a test for that.

**Comment by tkawachi** [comment]
Thank you for the feedback. I published 0.4.1 with the fix. (It may takes several hours to sync to maven central)
