### ISSUE TITLE
Depends on scalacheck even when scalacheck is not used

### ISSUE THREAD

**Issue by nrinaudo** [tkawachi/sbt-doctest#71]
I'm running a few tests that do not depend on scalacheck. I've also set things up so that sbt-doctest should not look for dependencies itself:

```scala
doctestWithDependencies := false
doctestTestFramework    := DoctestTestFramework.ScalaTest
```

Running the tests yields the following (truncated) error:

```
Caused by: java.lang.ClassNotFoundException: org.scalacheck.Test$TestCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.scalatest.tools.Framework$ScalaTestTask.loadSuiteClass(Framework.scala:399)
       [...]
```

Adding a scalacheck dependency in `build.sbt` solves the problem.

It's not a huge deal, but it would be better not to use scalacheck classes when scalacheck is not actually used.

If this is something you feel interesting, and you can point me in the right direction, I'd be happy to take a shot at a PR for this.

**Comment by tkawachi** [comment]
Hi @nrinaudo, it's good point.

Each subclass of `TestGen` generates .scala files based on parsed [ParsedDoctest](https://github.com/tkawachi/sbt-doctest/blob/a337e76cc86138e0d6251d3c2aa460b7d36650e1/src/main/scala/com/github/tkawachi/doctest/ParsedDoctest.scala).
Scalacheck codes can be skipped when `ParsedDoctest#components` doesn't contain [Verbatim](https://github.com/tkawachi/sbt-doctest/blob/a337e76cc86138e0d6251d3c2aa460b7d36650e1/src/main/scala/com/github/tkawachi/doctest/DoctestComponent.scala#L6).

**Comment by nrinaudo** [comment]
分かりました。
I'll try to put a PR sometime this week. Thanks!
