### ISSUE TITLE
Remove dependencies as preparation for porting to ScalaJS

### ISSUE THREAD

**Issue by frgomes** [tkawachi/sbt-doctest#80]
``ScalaJS`` does not provide several dependencies currently pulled in by ``sbt-doctest``, among them and possibly the most relevant of all is ``ScalaTest``.

This is a proposal intended to remove dependencies from ``ScalaTest`` and other test libraries, replacing them all by ``µTest``. In addition, dependencies from Apache  Lang3 and Apache Common-IO should also be removed.

**Comment by tkawachi** [comment]
Hi,
The default dependency to scalatest can be removed by setting `doctestWithDependencies := false`.
Apache lamg3 and commons-io are only used in this plugin code and not in generated tests. Can it be a problem when port to ScalaJS?

**Comment by frgomes** [comment]
IMHO, the easiest approach is simply replace all dependencies from ScalaTest by uTest, since uTest runs in all platforms. There are test classes which depend on ScalaTest and it's easy to get rid of it.

Dependencies from Lang3 and CommonIO can be avoided by picking the necessary classes and appending them to the source tree of the plugin.

I will send a PR for your review later.

**Comment by frgomes** [comment]
I'm observing excessive consume of CPU and memory when running scripted tests for html-entities.
Is it me or you also observe that?

**Comment by frgomes** [comment]
**UPDATE**
Dependencies from ScalaTest were replaced by uTest.
Dependencies from Apache Lang3 and Apache CommonsIO were not touched.
